=== ADARA-Neutrons/adara/doc/schemas/RunInfo/runinfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://public.sns.gov/schema/runinfo.xsd"
  xmlns="http://public.sns.gov/schema/runinfo.xsd"
  version="0.5"
  elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="runinfo">
    <xs:annotation>
      <xs:documentation>SNS runinfo root element.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="das_version" type="xs:string">
          <xs:annotation>
            <xs:documentation>Current DAS version: 4.3</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="facility_name" type="xs:string"/>
        <xs:element name="proposal_id" type="xs:string"/>
        <xs:element name="proposal_title" type="xs:string" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>Watch out for special characters typed by users, similar for all other user contributed fields, such as collection_title, run_title, sample details, and user_name.</xs:documentation>
          </xs:annotation>    
        </xs:element>
        <xs:element name="run_number" type="xs:string"/>
        <xs:element name="run_title" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="run_revision" minOccurs="0" maxOccurs="1"/>    
        <xs:element ref="sample" minOccurs="0" maxOccurs="1"/>
        <xs:element name="users">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="user" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>  
        </xs:element>
        <xs:element ref="reduction" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="run_revision">
    <xs:complexType>
      <xs:annotation>
        <xs:documentation>Capture change logs of raw data.</xs:documentation>
      </xs:annotation>
      <xs:all>
        <xs:element name="revision_number" type="xs:string"/>
        <xs:element name="revision_log" type="xs:string"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="sample">
    <xs:complexType>
      <xs:annotation>
        <xs:documentation>Sample information</xs:documentation>
      </xs:annotation>
      <xs:all>
        <xs:element name="name" type="xs:string"  minOccurs="0" maxOccurs="1"/>
        <xs:element name="id" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="nature" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="chemical_formula" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="environment" type="xs:string" minOccurs="0" maxOccurs="1"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="user">
    <xs:complexType>
      <xs:all>
        <xs:element name="id" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="role" type="xs:string" minOccurs="0" maxOccurs="1"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="binning_type">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:annotation>
          <xs:documentation>Currently we only have linear and log binning. Momentum transfer (Q) and d_spacing binning will need geometry information.</xs:documentation>
        </xs:annotation>
        <xs:pattern value="linear|log|momentum_transfer|d_spacing"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:group name="binning_parameters">
    <xs:sequence>
      <xs:element ref="binning_type"/>
      <xs:element name="units" type="xs:string">
        <xs:annotation>
          <xs:documentation>For linear and log binning, the default units is microsecond.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="start_bin" type="xs:float"/>
      <xs:element name="end_bin" type="xs:float"/>
      <xs:element name="bin_width" type="xs:float"/>
    </xs:sequence>  
  </xs:group>
  <xs:element name="reduction">
    <xs:complexType>
      <xs:annotation>
        <xs:documentation>Capture parameters needed for automatic data reduction.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
        <xs:element name="detector_binning" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:group ref="binning_parameters"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="beam_monitor_binning" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="beam_monitor_name" type="xs:string" minOccurs="0"/>
              <xs:element name="beam_monitor_id" type="xs:string" minOccurs="0"/>
              <xs:element name="beam_monitor_description" type="xs:string" minOccurs="0"/>              
              <xs:group ref="binning_parameters"/>      
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ADARA-Neutrons/adara/doc/schemas/RunInfo/RunInfo.Sample.xml
<?xml version="1.0"?>
<runinfo 
 xmlns="http://public.sns.gov/schema/runinfo.xsd"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://public.sns.gov/schema/runinfo.xsd http://public.sns.gov/schema/runinfo.xsd">
    <das_version>4.3</das_version>
    <facility_name>SNS</facility_name>
    <proposal_id>IPTS-12345</proposal_id>
    <proposal_title>How to make a Better Cup of Coffee! :-D</proposal_title>
    <run_number>24680</run_number>
    <run_title>Run! Now! Save Yourself! :-o</run_title>
    <run_revision>
    <revision_number>3</revision_number>
    <revision_log>3 Strikes, Yer Out... :-}</revision_log>
    </run_revision>
    <sample>
    <name>Some Stuff I Found in the Back of My Frig...</name>
    <id>SCUM-123</id>
    <nature>liquid</nature>
    <chemical_formula>H2-SO4</chemical_formula>
    <environment>H2-SO4</environment>
    </sample>
    <users>
    <user>
    <id>xyz</id>
    <name>Jeeeeeeeeeeeeeeeeeeeeeeeem</name>
    </user>
    <user>
    <id>xuy</id>
    <name>XingXing Marie Yao</name>
    </user>
    </users>
    <reduction>
    <detector_binning>
        <binning_type>linear</binning_type>
        <units>microsecond</units>
        <start_bin>0.1234</start_bin>
        <end_bin>9876.5432</end_bin>
        <bin_width>1020.3040</bin_width>
    </detector_binning>
    <beam_monitor_binning>
        <beam_monitor_name>White Beam</beam_monitor_name>
        <beam_monitor_id>0</beam_monitor_id>
        <beam_monitor_description>All Neutrons</beam_monitor_description>
        <binning_type>log</binning_type>
        <units>microsecond</units>
        <start_bin>1.3579</start_bin>
        <end_bin>8642.1234</end_bin>
        <bin_width>246.810</bin_width>
    </beam_monitor_binning>
    </reduction>
</runinfo>

=== ADARA-Neutrons/adara/doc/schemas/RunInfo/runinfo_BSS_19654.xml
<?xml version="1.0" encoding="UTF-8"?>
<runinfo 
    xmlns="http://public.sns.gov/schema/runinfo.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://public.sns.gov/schema/runinfo.xsd http://public.sns.gov/schema/runinfo.xsd">
    <das_version>4.3</das_version>
    <facility_name>SNS</facility_name>
    <proposal_id>IPTS-6627</proposal_id>
    <proposal_title>Slow lattice dynamics in the relaxor ferroelectric PMN-30%PT</proposal_title>
    <run_number>19654</run_number>
    <run_title>_No10</run_title>
    <users>
        <user>
            <id>GUANGYONG</id>
            <role>V</role>
        </user>
        <user>
            <id>CSTOCK</id>
            <role>V</role>
        </user>
        <user>
            <id>PMGEHRING</id>
            <role>V</role>
        </user>
        <user>
            <id>JWEN</id>
            <role>V</role>
        </user>
        <user>
            <id>ZHIJUNXU</id>
            <role>V</role>
        </user>
        <user>
            <id>MASAMATSUURA</id>
            <role>PI</role>
        </user>
    </users>
    <reduction>
        <detector_binning>
            <binning_type>linear</binning_type>
            <units>microsecond</units>
            <start_bin>0.0</start_bin>
            <end_bin>200010.0</end_bin>
            <bin_width>10.0</bin_width>
        </detector_binning>
        <beam_monitor_binning>
            <beam_monitor_name>BEAMMON1</beam_monitor_name>
            <beam_monitor_id>1</beam_monitor_id>
            <beam_monitor_description>beam monitor</beam_monitor_description>
            <binning_type>linear</binning_type>
            <units>microsecond</units>
            <start_bin>0.0</start_bin>
            <end_bin>200001.0</end_bin>
            <bin_width>1.0</bin_width>
        </beam_monitor_binning>
    </reduction>
</runinfo>
