=== ADARA-Neutrons/adara/doc/schemas/DeviceDescriptor/device.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://public.sns.gov/schema/device.xsd"
  xmlns="http://public.sns.gov/schema/device.xsd"  
  version="0.5"
  elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xsd:element name="device">
    <xsd:annotation>
      <xsd:documentation>SNS device descriptor root element.</xsd:documentation>
    </xsd:annotation>  
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="device_name" type="xsd:string"/>  
        <xsd:element name="device_description" type="xsd:string" minOccurs="0" maxOccurs="1"/>  
        <xsd:choice>
          <xsd:sequence>
            <xsd:annotation>
              <xsd:documentation>DAS application details.</xsd:documentation>
            </xsd:annotation>
            <xsd:element name="app_id" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="app_version" type="xsd:string" minOccurs="0" maxOccurs="1"/>
          </xsd:sequence>
          <xsd:sequence>
            <xsd:annotation>
              <xsd:documentation>EPICS IOC details.</xsd:documentation>
            </xsd:annotation>
            <xsd:element name="ioc_name" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="ioc_script" type="xsd:string" minOccurs="0" maxOccurs="1"/>   
            <xsd:element name="ioc_console_port" type="xsd:string" minOccurs="0" maxOccurs="1"/>            
          </xsd:sequence>
        </xsd:choice>       
        <xsd:element ref="enumerations" minOccurs="0" maxOccurs="1">
          <xsd:annotation>
            <xsd:documentation>Shared enumerations accross all devices (enum_00 and enum_01 in device descriptor of virtual device 0) or across one device.</xsd:documentation>
          </xsd:annotation>            
        </xsd:element>
        <xsd:element ref="process_variables"/>  
        <xsd:element name="serial_number" type="xsd:string" minOccurs="0" maxOccurs="1">
          <xsd:annotation>
            <xsd:documentation>Could also be used for globally unique device identifier, such as barcode.</xsd:documentation>
          </xsd:annotation>         
        </xsd:element>
        <xsd:element ref="manufacturer" minOccurs="0" maxOccurs="1"/>   
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>  
  <xsd:element name="process_variables">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="process_variable" minOccurs="0" maxOccurs="unbounded"/>        
      </xsd:sequence>  
    </xsd:complexType>  
  </xsd:element>
  <xsd:element name="process_variable">
    <xsd:complexType>
      <xsd:sequence>        
        <xsd:element name="pv_name" type="xsd:string">
          <xsd:annotation>
            <xsd:documentation>
              (Friendly) name of the process variable. 
            </xsd:documentation>
          </xsd:annotation>
        </xsd:element>
        <xsd:element name="pv_id" type="xsd:unsignedInt">
          <xsd:annotation>
            <xsd:documentation>Locally unique for each device. 32 bit unsigned integer, 0 to 4,294,967,295.</xsd:documentation>
          </xsd:annotation>
        </xsd:element>  
        <xsd:choice minOccurs="0" maxOccurs="1">
          <xsd:sequence>
            <xsd:annotation>
              <xsd:documentation>National Instrument data sockets details.</xsd:documentation>
            </xsd:annotation>
            <xsd:element name="pv_nids_read" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="pv_nids_write" type="xsd:string" minOccurs="0" maxOccurs="1"/>   
          </xsd:sequence>
          <xsd:element name="pv_epics_name" type="xsd:string" minOccurs="0" maxOccurs="1">
            <xsd:annotation>
              <xsd:documentation>
                Alias of an epics pv. Skip pv_epics_name if no alias.
                
                Please note a virtual pv, such as num_active_devices from device 0 won't have data sockets or pv_epics_name.
              </xsd:documentation>
            </xsd:annotation>     
          </xsd:element>
        </xsd:choice>
        <xsd:element name="pv_description" type="xsd:string" minOccurs="0" maxOccurs="1"/>
        <xsd:element name="pv_type">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:annotation>
                <xsd:documentation>
                  unsigned integer: unsigned 32 bit value.
                  signed integer: signed 32 bit value. TODO: need to add to design document. 
                  boolean: a subset of the unsigned integer type with 0 as False and 1 as True. Actual variable updates come as u32 packet.
                  double: IEEE 754 double floating point value. 
                  string: UTF-8 encoded string.
                  two-tuple: Time_of_flight and value pair for fast metadata. TODO: add two-tuple details in design document.
                  enum_[0-9][0-9]: Use shared enumerations. TODO: need extra step to validate against shared enumerations beyond the regular expression.
                </xsd:documentation>
              </xsd:annotation>         
              <xsd:pattern value="unsigned integer|signed integer|boolean|double|string|two-tuple|enum_[0-9][0-9]"/>                  
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="pv_units" type="xsd:string" minOccurs="0" maxOccurs="1">
          <xsd:annotation>
            <xsd:documentation>TODO: generate and maintain a list of standardized units somewhere to validate against.</xsd:documentation>
          </xsd:annotation>
        </xsd:element>     
        <xsd:element name="pv_min_value" minOccurs="0" maxOccurs="1">
          <xsd:annotation>
            <xsd:documentation>Lower bound (inclusive?) for numeric values, the type should be consistent to the one specified by pv_type. TODO: validate type?</xsd:documentation>
          </xsd:annotation> 
        </xsd:element> 
        <xsd:element name="pv_max_value" minOccurs="0" maxOccurs="1">
          <xsd:annotation>
            <xsd:documentation>Upper bound (inclusive?) for numeric values, the type should be consistent to the one specified by pv_type. TODO: validate type</xsd:documentation>
          </xsd:annotation> 
        </xsd:element> 
        <xsd:element ref="pv_hint" minOccurs="0" maxOccurs="1"/>            
      </xsd:sequence>           
    </xsd:complexType>  
  </xsd:element>  
  <xsd:element name="pv_hint">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="pv_nexus_link" minOccurs="0" >
          <xsd:annotation>
            <xsd:documentation>
              pv_nexus_link holds full XPath path expression (with *intended name* if different from pv_name) to indicate where inside NeXus files a link needs to be created with target as "/entry/DASlogs/pv_name".
            </xsd:documentation>
          </xsd:annotation> 
        </xsd:element> 
        <xsd:element name="pv_nexus_type" minOccurs="0" maxOccurs="1">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:annotation>
                <xsd:documentation>
                  pv_nexus_type sets "NXpositioner" as the type for /entry/DASlogs/pv_name in NeXus files for all PVs come from DAS motor config files.
                </xsd:documentation>
              </xsd:annotation>         
              <xsd:pattern value="NXpositioner"/>                  
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
      </xsd:sequence> 
    </xsd:complexType>      
  </xsd:element>  
  <xsd:element name="enumerations">
    <xsd:annotation>
      <xsd:documentation>Locally defined enumerations. Each enumeration can be used as pv_type for multiple process variables of this device. Naming convention: enum_00 to enum_99.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="enumeration" minOccurs="0" maxOccurs="unbounded"/>        
      </xsd:sequence>  
    </xsd:complexType>  
  </xsd:element>
  <xsd:element name="enumeration">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="enum_name">
          <xsd:annotation>
            <xsd:documentation>
              enum_00 to enum_49: enumerations shared across all devices.
              enum_50 to enum_99: enumerations shared across one device.
            </xsd:documentation>
          </xsd:annotation>
          <xsd:simpleType>
            <xsd:restriction base="xsd:string"> 
              <xsd:pattern value="enum_[0-9][0-9]">     
              </xsd:pattern>      
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>          
        <xsd:element ref="enum_element" minOccurs="1" maxOccurs="unbounded"/>                                  
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element> 
  <xsd:element name="enum_element">
    <xsd:complexType>
      <xsd:sequence>        
        <xsd:element name="enum_element_name" type="xsd:string"/>              
        <xsd:element name="enum_element_value" type="xsd:integer"/>                  
      </xsd:sequence>           
    </xsd:complexType>  
  </xsd:element>  
  <xsd:element name="manufacturer">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="manufacturer_name" minOccurs="0" maxOccurs="1" type="xsd:string"/>
        <xsd:element name="manufacturer_phone" minOccurs="0" maxOccurs="1" type="xsd:string"/>
        <xsd:element name="manufacturer_email" minOccurs="0" maxOccurs="1" type="xsd:string"/>          
      </xsd:sequence>  
    </xsd:complexType>  
  </xsd:element>  
</xsd:schema>

=== ADARA-Neutrons/adara/doc/schemas/DeviceDescriptor/a2r_motor.xml
<?xml version="1.0" encoding="UTF-8"?>
<device xmlns="http://public.sns.gov/schema/device.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://public.sns.gov/schema/device.xsd http://public.sns.gov/schema/device.xsd">
    <device_name>a2r_motor</device_name>
    <device_description>One of the four motors for Slit 2. Based on HYSPEC motorsConfigFile.xml, motorsOptionsFile.xml, and motorsUnitsFile.xml.</device_description>
    <app_id>1031</app_id>
    <enumerations>
      <enumeration>
        <enum_name>enum_51</enum_name>
        <!-- Motor status enumeration. Repeat in each and every motor's descriptor.-->
        <enum_element>
            <enum_element_name>UNKNOWN</enum_element_name>
            <enum_element_value>0</enum_element_value>
        </enum_element> 
        <enum_element>
            <enum_element_name>ACTIONREQ</enum_element_name>
            <enum_element_value>1</enum_element_value>
        </enum_element> 
        <enum_element>
            <enum_element_name>MOVING</enum_element_name>
            <enum_element_value>2</enum_element_value>
        </enum_element> 
        <enum_element>
            <enum_element_name>ATPOSITION</enum_element_name>
            <enum_element_value>3</enum_element_value>
        </enum_element> 
        <enum_element>
            <enum_element_name>OFFTARGET</enum_element_name>
            <enum_element_value>4</enum_element_value>
        </enum_element> 
        <enum_element>
            <enum_element_name>POSLIM</enum_element_name>
            <enum_element_value>5</enum_element_value>
        </enum_element> 
        <enum_element>
            <enum_element_name>NEGLIM</enum_element_name>
            <enum_element_value>6</enum_element_value>
        </enum_element> 
        <enum_element>
            <enum_element_name>PROBSTOP</enum_element_name>
            <enum_element_value>7</enum_element_value>
        </enum_element> 
        <enum_element>
            <enum_element_name>ABORTED</enum_element_name>
            <enum_element_value>8</enum_element_value>
        </enum_element> 
        <enum_element>
            <enum_element_name>OVERRIDDEN</enum_element_name>
            <enum_element_value>9</enum_element_value>
        </enum_element> 
        <enum_element>
            <enum_element_name>VETOED</enum_element_name>
            <enum_element_value>10</enum_element_value>
        </enum_element> 
        <enum_element>
            <enum_element_name>COMERR</enum_element_name>
            <enum_element_value>11</enum_element_value>
        </enum_element> 
        <enum_element>
            <enum_element_name>DRVERR</enum_element_name>
            <enum_element_value>12</enum_element_value>
        </enum_element> 
        <enum_element>
            <enum_element_name>REQERR</enum_element_name>
            <enum_element_value>13</enum_element_value>
        </enum_element> 
        <enum_element>
            <enum_element_name>MOVEERR</enum_element_name>
            <enum_element_value>14</enum_element_value>
        </enum_element>
      </enumeration> 
    </enumerations>        
    <process_variables>
      <process_variable>
          <pv_name>a2r</pv_name>
          <pv_id>0</pv_id>
          <pv_nids_read>dstp://motors/Position[5]</pv_nids_read>
          <pv_type>double</pv_type>
          <pv_units>millimetre</pv_units>
          <pv_hint>
              <pv_nexus_link>/NXroot/NXinstrument/NXaperture[@name="aperture2"]/a2r</pv_nexus_link>
              <pv_nexus_type>NXpositioner</pv_nexus_type>              
          </pv_hint>   
      </process_variable>
        <process_variable>
            <pv_name>a2rRequest</pv_name>
            <pv_id>1</pv_id>
            <pv_nids_read>dstp://motors/Request[5]</pv_nids_read>
            <pv_nids_write>dstp://motors/RequestRem[5]</pv_nids_write>
            <pv_type>double</pv_type>
            <pv_units>millimetre</pv_units>
            <pv_hint>
                <pv_nexus_type>NXpositioner</pv_nexus_type>              
            </pv_hint>   
        </process_variable>
        <process_variable>
            <pv_name>a2rStatus</pv_name>
            <pv_id>2</pv_id>
            <pv_nids_read>dstp://motors/RStatus[5]</pv_nids_read>
            <pv_type>enum_51</pv_type>
            <pv_hint>
                <pv_nexus_type>NXpositioner</pv_nexus_type>              
            </pv_hint> 
        </process_variable>      
    </process_variables>
    <serial_number>200E</serial_number>
</device>

=== ADARA-Neutrons/adara/doc/schemas/DeviceDescriptor/EPICS_2-D_translation_table.xml
<?xml version="1.0" encoding="UTF-8"?>
<device xmlns="http://public.sns.gov/schema/device.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://public.sns.gov/schema/device.xsd http://public.sns.gov/schema/device.xsd">
    <device_name>2-D Translation Table</device_name>
    <ioc_name>Simulation</ioc_name>
    <ioc_script>/home/epics/R3.14.12.2/applications/bl99/simulation/st.cmd</ioc_script>
    <ioc_console_port>4812</ioc_console_port>
    <process_variables>
        <process_variable>
            <pv_name>active</pv_name>
            <pv_id>0</pv_id>
            <pv_type>boolean</pv_type>
            <pv_hint>
                <pv_nexus_type>NXpositioner</pv_nexus_type>              
            </pv_hint> 
        </process_variable>
        <process_variable>
            <pv_name>xpos</pv_name>
            <pv_id>1</pv_id>
            <pv_epics_name>motor_x</pv_epics_name> <!-- Readable and writable, similar to pv "s1lRequest" in current das. -->
            <pv_type>signed integer</pv_type>
            <pv_hint>
                <pv_nexus_type>NXpositioner</pv_nexus_type>              
            </pv_hint> 
        </process_variable>
        <process_variable>
            <pv_name>xpos_readback</pv_name>
            <pv_id>2</pv_id>
            <pv_epics_name>motor_x</pv_epics_name> <!-- Readable, similar to pv "s1l" in current das. -->
            <pv_type>signed integer</pv_type>
            <pv_hint>
                <pv_nexus_type>NXpositioner</pv_nexus_type>              
            </pv_hint> 
        </process_variable>  
    </process_variables>
</device>

=== ADARA-Neutrons/adara/doc/schemas/DeviceDescriptor/device_0.xml
<?xml version="1.0" encoding="UTF-8"?>
<device xmlns="http://public.sns.gov/schema/device.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://public.sns.gov/schema/device.xsd http://public.sns.gov/schema/device.xsd">
    <device_name>VirtualDevice0</device_name>
    <device_description>Virtual device for sharing enumerations and other useful information across devices.</device_description>
    <enumerations>
        <enumeration>
            <enum_name>enum_00</enum_name>
            <!-- PV status enumeration, see design doc Table 7.-->
            <enum_element>
                <enum_element_name>None</enum_element_name>
                <enum_element_value>0</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>Read</enum_element_name>
                <enum_element_value>1</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>Write</enum_element_name>
                <enum_element_value>2</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>HiHi</enum_element_name>
                <enum_element_value>3</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>High</enum_element_name>
                <enum_element_value>4</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>LoLo</enum_element_name>
                <enum_element_value>5</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>Low</enum_element_name>
                <enum_element_value>6</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>State</enum_element_name>
                <enum_element_value>7</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>Cos</enum_element_name>
                <enum_element_value>8</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>Comm</enum_element_name>
                <enum_element_value>9</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>Timeout</enum_element_name>
                <enum_element_value>10</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>HwLimit</enum_element_name>
                <enum_element_value>11</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>Calc</enum_element_name>
                <enum_element_value>12</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>Scan</enum_element_name>
                <enum_element_value>13</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>Link</enum_element_name>
                <enum_element_value>14</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>Soft</enum_element_name>
                <enum_element_value>15</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>BadSub</enum_element_name>
                <enum_element_value>16</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>UDF</enum_element_name>
                <enum_element_value>17</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>Disable</enum_element_name>
                <enum_element_value>18</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>Simm</enum_element_name>
                <enum_element_value>19</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>ReadAccess</enum_element_name>
                <enum_element_value>20</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>WriteAccess</enum_element_name>
                <enum_element_value>21</enum_element_value>
            </enum_element>
        </enumeration>
        <enumeration>
            <enum_name>enum_01</enum_name>
            <!-- PV alarm severity enumeration, see design doc Table 8.-->
            <enum_element>
                <enum_element_name>No Alarm</enum_element_name>
                <enum_element_value>0</enum_element_value>
            </enum_element> 
            <enum_element>
                <enum_element_name>Minor</enum_element_name>
                <enum_element_value>1</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>Major</enum_element_name>
                <enum_element_value>2</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>Invalid</enum_element_name>
                <enum_element_value>3</enum_element_value>
            </enum_element>
        </enumeration>
    </enumerations>       
    <process_variables>
        <process_variable>
            <pv_name>num_active_devices</pv_name>
            <pv_id>0</pv_id>
            <pv_description>Total number of active devices for a run</pv_description>
            <pv_type>unsigned integer</pv_type>
            <pv_min_value>0</pv_min_value>         
        </process_variable>
     </process_variables>
</device>

=== ADARA-Neutrons/adara/doc/schemas/DeviceDescriptor/motors_stop_button.xml
<?xml version="1.0" encoding="UTF-8"?>
<device xmlns="http://public.sns.gov/schema/device.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://public.sns.gov/schema/device.xsd http://public.sns.gov/schema/device.xsd">
    <device_name>MotorsStopButton</device_name>
    <device_description>From ArcsMotorsConfigFile. Note the pv is only writable.</device_description>
    <app_id>1031</app_id>
    <enumerations>
        <enumeration>
            <enum_name>enum_50</enum_name>
            <enum_element>
                <enum_element_name>UNDEFINED</enum_element_name>
                <enum_element_value>0</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>NOTPUSHED</enum_element_name>
                <enum_element_value>1</enum_element_value>
            </enum_element>
            <enum_element>
                <enum_element_name>PUSHED</enum_element_name>
                <enum_element_value>27384</enum_element_value>
            </enum_element>
        </enumeration>       
    </enumerations>
    <process_variables>
        <process_variable>
            <pv_name>MotorsStopButton</pv_name>
            <pv_id>0</pv_id>
            <pv_nids_write>dstp://motors/MotorsStopButton</pv_nids_write>
            <pv_type>enum_50</pv_type>
            <pv_hint>
                <pv_nexus_type>NXpositioner</pv_nexus_type>              
            </pv_hint> 
        </process_variable>  
    </process_variables>
    <serial_number>200G</serial_number>
</device>
